# Reinforcement Learning on Hamster

In [1]:
import gym
import gym.spaces
import time
import numpy as np
from collections import defaultdict, deque
import sys
env = gym.make('HamsterExperiment-v0')

/Users/admin/miniconda2/lib/python2.7/site-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ufuncs import *
/Users/admin/miniconda2/lib/python2.7/site-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._solve_toeplitz import levinson
/Users/admin/miniconda2/lib/python2.7/site-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._decomp_update import *
/Users/admin/miniconda2/lib/python2.7/site-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
/Users/admin/miniconda2/lib/python2.7/site-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size cha

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!

slippery!



In [2]:
# introduce map

In [7]:
def sarsa(env, num_episodes, alpha, gamma=1.0):
    # initialize action-value function (empty dictionary of arrays)
    Q = defaultdict(lambda: np.zeros(env.nA))
    # initialize performance monitor
    # loop over episodes
    for i_episode in range(1, num_episodes+1):
        # monitor progress
        if i_episode % 100 == 0:
#             print("\rEpisode {}/{}".format(i_episode, num_episodes), end="")
            print("\rEpisode {}/{}.".format(i_episode, num_episodes),)
            sys.stdout.flush()   
        
        ## TODO: complete the function
        
        # Set epsilon
        epsilon = 1./(1.+i_episode)
        # Observe S_0, t<-0
        state = env.reset()
        # Get A_0 from Q (epsilon-greedy policy) for this state
        policy_state = epsilon_greedy_policy(env, Q[state], epsilon)
        action = np.random.choice(np.arange(env.nA), p=policy_state)
        
        # Repeat until terminal state reached
        while True:
            # Take A_t, get R_(t+1), S_(t+1)
            state_next, reward, done, info = env.step(action)
            
            # Choose A_(t+1) from Q (from policy for S_(t+1))
            policy_state = epsilon_greedy_policy(env, Q[state_next], epsilon)
            action_next = np.random.choice(np.arange(env.nA), p=policy_state)
            # Get G_t
            G_t = reward + gamma*Q[state_next][action_next]
            # Update action value function
            Q[state][action] = Q[state][action] + alpha*(G_t - Q[state][action])
#             print (Q[state][action])
            
            # print
            if i_episode > 5000:
                import os
                os.system('cls')
                from IPython.display import clear_output
                clear_output(wait=True)
                env.render()
                sys.stdout.flush()
            
            # Check if reached terminal state
            if done:
                break
            # Update state & action for next step
            state = state_next
            action = action_next
        
    return Q

def epsilon_greedy_policy(env, Q_state, epsilon):
    # Get greedy action (gives highest Q for state)
    greedy_action = np.argmax(Q_state)
    # Get number of possible actions     
    nA = env.nA
    # Use epsilon to get probability distribution to use in policy for state
    policy_state = np.ones(nA) * epsilon / nA
    policy_state[greedy_action] = 1 - epsilon + (epsilon / nA)
    return policy_state

def greedy_policy(env, Q_state):
    # Get greedy action (gives highest Q for state)
    greedy_action = np.argmax(Q_state)
    # Get number of possible actions     
    nA = env.nA
    policy_state = np.zeros(nA)
    policy_state[greedy_action] = 1
    return policy_state

def final_policy(env, Q):
    # Observe S_0, t<-0
    coords = [env.get_start()]
    state = env.reset()
    # Get A_0 from Q (epsilon-greedy policy) for this state
    policy_state = greedy_policy(env, Q[state])
    action = np.random.choice(np.arange(env.nA), p=policy_state)
        
    # Repeat until terminal state reached
    while True:
        # Take A_t, get R_(t+1), S_(t+1)
        state_next, reward, done, info = env.step(action)
            
        # Choose A_(t+1) from Q (from policy for S_(t+1))
        policy_state = greedy_policy(env, Q[state_next])
        action_next = np.random.choice(np.arange(env.nA), p=policy_state)
            
        coords.append(np.unravel_index(state_next, env.get_shape()))
            
        # Check if reached terminal state
        if done:
            break
        # Update state & action for next step
        state = state_next
        action = action_next
        
    return coords

In [8]:
# obtain the estimated optimal policy and corresponding action-value function
Q_sarsa = sarsa(env, 5010, .01)

# print the estimated optimal policy
policy_sarsa = np.array([np.argmax(Q_sarsa[key]) if key in Q_sarsa else -1 for key in np.arange(7*12)]).reshape(7,12)
print("\nEstimated Optimal Policy (UP = 0, RIGHT = 1, DOWN = 2, LEFT = 3, N/A = -1):")
print(policy_sarsa)


# transform quality map into actions
# start = env.get_start()
# for col in policy_sarsa:
#     for row in col:
#         if (col,row) == start:
list_of_coords = final_policy(env, Q_sarsa)
print(list_of_coords)

# plot the estimated optimal state-value function
V_sarsa = ([np.max(Q_sarsa[key]) if key in Q_sarsa else 0 for key in np.arange(48)])

v1.1
□  □  □  □  □  □  □  □  □  □  □  □
□  □  □  □  □  □  □  □  □  □  □  □
□  □  □  □  □  □  □  □  □  □  □  □
□  □  □  □  □  □  □  □  □  □  □  □
□  □  □  □  □  □  □  □  □  □  □  □
□  ×  ×  ×  ×  ×  ×  ×  ×  ×  ×  ★
□  □  □  □  □  □  □  □  □  □  □  □


Estimated Optimal Policy (UP = 0, RIGHT = 1, DOWN = 2, LEFT = 3, N/A = -1):
[[ 1  3  2  1  1  1  0  0  1  1  3  3]
 [ 3  0  1  2  1  2  2  2  0  0  2  2]
 [ 1  2  2  1  0  2  2  2  2  2  2  2]
 [ 1  1  1  1  1  3  1  2  2  2  2  0]
 [ 1  0  0  0  3  0  3  1  3  1  1  2]
 [ 0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0]
 [ 0  1  1  1  1  1 -1 -1 -1 -1 -1 -1]]
[(6, 0), (5, 0), (4, 0), (4, 1), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 11)]


In [15]:
%run -i '/Users/admin/Documents/Hamster/lab6/run.py'

ImportError: No module named PyObjCTools